name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release version
        id: get_version
        run: |
          RELEASE_VERSION=$(jq -r .version manifest.json)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Version: $RELEASE_VERSION"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: "Automatically created release for push on the main branch."
          assets: main.js,manifest.json,styles.css,versions.json
